spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: xxxxxddfdfdfdfdfdfdf
    username: rsdfsdf
    password: 1234sdfsdf
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
