server:
  port: 9000
  servlet:
    context-path: /

spring:
  jackson:
    date-format: yyyy-MM-dd HH-mm
  profiles:
    active:
      - database
      - oauth2
      - jwt
      - cors


springdoc:
  swagger-ui:
    path: /
    csrf:
      enabled: true

logging:
  level:
    com.burntbean.burntbean: DEBUG
    org.springframework.web: INFO
